services:
  goapp:
    build:
      context: ./
      dockerfile: images/Dockerfile
    volumes:
      - ../../.:/app
    environment:
      - GO_ROOTPATH=/app
    ports:
      - "8181:8181"

  mongodb:
    image: mongo:8.0.3
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev123

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/